spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fin
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize : true

jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: passw0rd
  sql:
    init:
      mode: always
      schema-locations: classpath:data.sql

logging:
  level:
    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
